version: "2"
services:
  checker:
    image: docker.pkg.github.com/clabroche/docker-registry/theemmerdor:latest
    hostname: theemmerdor
    restart: always
    networks:
      - web
    environment:
      PORT: 4512
      PASSWORD: "a password to protect front"
      DISCORD_TOKEN: token from your discord bot dashboard
      PRISON_TOKEN: token for prison from you discord bot dashboard (must to be different of DISCORD_TOKEN)
      CHANNEL_ID: Id of the channel where command of the bot can be written
    volumes:
      - where you want/configs:/theemmerdor/configs
      - where you want/sound:/theemmerdor/sounds
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.http.services.theemmerdor.loadbalancer.server.port: 4512
      traefik.http.routers.theemmerdor.entrypoints: secure
      traefik.http.routers.theemmerdor.rule: Host(`the-emmerdor.yourdomain.fr`)
      traefik.http.routers.theemmerdor.tls: true
      traefik.http.routers.theemmerdor.tls.certresolver: letsencrypt

networks:
  web:
    external: true